// Prompts the user copies into their coding agent when the importer cannot
// go further on its own. Every prompt states what the app was doing, what
// it said (with the concrete facts from the response), what the agent should
// do, which guides govern the work, and what to report back.
// Prompts that let the agent retry the import end with `rerunBlock`.
//
// The app stages every upload of a batch it could not import under the
// project's own tmp/, so a prompt names the file by a path relative to the
// project the agent starts in and never asks the user to find it again.
//
// The guides ship inside dbu6, which in a user's project is an installed
// package: a prompt names the command that prints a guide (\`dbu6 docs\`),
// never a file of ours, and says that what the agent writes goes in the
// project's own directories.
//
// Each prompt takes the server's own reply for its case, a plan file or an
// account's refusal, and reads the contract's fields as they are named.

import { guideCommand, type AutoImportPlanFile } from "../../../shared/index";
import { PII_RULE, PROJECT_FILES_RULE } from "../../agent-prompt-rules";
import { parserLabel } from "../../format";
import type { AccountRefusal, RefusalOf } from "./outcome";

type PlanFile<Status extends AutoImportPlanFile["status"]> = Extract<
  AutoImportPlanFile,
  { status: Status }
>;

const PARSERS_GUIDE = guideCommand("parsers");
const PARSER_GUIDE = guideCommand("parser-guide");
const BOOKS_GUIDE = guideCommand("books");

// A prompt names a parser as the app does, by its directory name.
const SAVED_PARSERS_NOTE = `A saved parser is named by its directory: the one of that name in this
project's custom-built-parsers/, or else the one bundled with dbu6, which
\`${PARSERS_GUIDE}\` lists.`;

// How a prompt has the agent change the import presets: the app's
// import_presets table, one institution per row with the parsers that read
// its statements and the accounts they import into. Changes go through the
// one route that checks them, never through a file.
const PRESET_CHANGES_NOTE = `The import presets are in the app, one institution per row, each listing the
saved parsers that read its statements and the accounts they import into.
Change them only through the app, never by editing a file:

  sapporta api get /api/import-presets
  sapporta api post /api/import-presets/changes --body '{"changes":[...]}'

An account names its ledger account by id; find it with
\`sapporta rows list accounts --where '{"name":{"eq":"<name>"}}'\`.
Run \`${BOOKS_GUIDE}\` for these calls and each change's fields.`;

function rerunBlock(paths: readonly string[]): string {
  const uploads = paths.map((path) => `    -F "files=@${path}"`).join(" \\\n");
  return `Re-running the import yourself: with the dev server running, POST the statement
file(s) to the same endpoint the screen uses. You need an agent access token,
which I can create from my account page in the app, in SAPPORTA_API_TOKEN.

  curl -sS -X POST "$SAPPORTA_API_URL/api/import-draft/statements/auto" \\
    -H "Authorization: Bearer $SAPPORTA_API_TOKEN" \\
${uploads}

A 200 response has \`files\` (how each upload was recognised and which account
it went to) and \`groups\` (one per account: draft_transaction_count,
transaction_count, duplicate_count, skipped_reconciled_count,
balance_metadata, statement_period, reconciliation_checkpoint). Errors are
4xx/5xx JSON with an \`error\` code and a \`message\`. Imports only create Draft
transactions; they never post to the books.`;
}

// Where the agent will find an upload: the staged copy inside this
// project, or the name the user dropped when the app kept none.
function stagedAt(file: {
  file_name: string;
  saved_path: string | null;
}): string {
  return file.saved_path ?? file.file_name;
}

function quoted(message: string): string {
  return `\nServer message: "${message}"\n`;
}

function list(items: readonly string[]): string {
  return items.join(", ");
}

// How a parser is written, the same wherever the app asks for one: the
// guides, then steps 1 to 5. The caller numbers on from 6.
function parserWritingSteps(): string {
  return `Run \`${PARSERS_GUIDE}\` and \`${PARSER_GUIDE}\`, and follow the two guides
they print exactly. ${PROJECT_FILES_RULE} In particular:

1. Check whether an existing parser, in custom-built-parsers/ or among the
   bundled ones the first guide lists, already handles this bank and layout.
   Extend it only if it is the same bank and the same layout; otherwise add a
   new directory under custom-built-parsers/ with fingerprint.md, parser.py,
   parser_test.py, and a sanitized fixture generated by a script.
2. Inspect that file and write a strict fingerprint. The parser must reject
   any other layout and any malformed row instead of skipping it, and must only
   write output after every check passes.
3. Emit the account or card number the statement prints about itself as
   \`account\`, and the institution name exactly as printed as \`institution\`.
4. Validate the opening balance, the closing balance, every running balance the
   statement prints, and any totals it prints.
5. ${PII_RULE}`;
}

export function unrecognizedPrompt(file: PlanFile<"unrecognized">): string {
  const tried =
    file.candidate_parser_paths.length === 0
      ? "There is no saved parser at all for this file extension yet."
      : `The parsers it tried and that rejected the file were: ${list(file.candidate_parser_paths)}.`;
  return `I tried to import a bank statement into my books app (dbu6, run from this project) through
the automatic importer at /import. It said no saved parser
recognised the file, so nothing was imported. Please build a deterministic
parser for this statement format so the import works.

The file is in this project at ${stagedAt(file)}.
Ask me which bank and which of my accounts it belongs to if the file doesn't
make that obvious. ${tried}

${parserWritingSteps()}
6. Tie the parser to my account in the import presets, as below. If an
   institution there already covers this bank, add the parser to it by its
   directory name (add_parser); otherwise add the institution with the parser
   (add_institution). If my account is not among the institution's accounts
   yet, add it (add_account) with account_identifiers set to the identifier
   the parser emits; ask me for its name, its ledger account and whether it
   is a credit card.
7. Run the parser on that file and on the fixture, run the tests, and report
   the opening balance, closing balance, date range, and row count you found so
   I can check them against the statement.

${PRESET_CHANGES_NOTE}

When you are done, tell me. I will drop the file into the importer again myself.`;
}

export function ambiguousPrompt(file: PlanFile<"ambiguous">): string {
  return `The automatic statement importer of my books app (dbu6, run from this project)
(POST /api/import-draft/statements/auto, screen /import)
reported that ${file.file_name} matched more than one saved parser:
${list(file.matching_parser_paths)}. Auto-detection requires exactly one match,
so nothing was imported.

${fingerprintTightening(stagedAt(file))}

Tell me when it is done and I will retry the import.`;
}

// Two parsers claim one file: how to part them, for the file at `path`.
function fingerprintTightening(path: string): string {
  return `Tighten the fingerprints of those parsers (run \`${PARSERS_GUIDE}\` for the
conventions, and read each parser's fingerprint.md) so that each rejects the other's layout at
the first structural check, add a parser_test.py case in each that asserts the
other's fixture is rejected, and keep every existing fixture passing. Do not
loosen any validation to get there. ${PII_RULE}

${PROJECT_FILES_RULE}

The file is in this project at ${path}.
Run each parser against it and confirm exactly one accepts it.`;
}

// The account a statement goes to isn't set up: no institution lists its
// parser, or the one that does has no accounts.
export function noAccountPrompt(file: PlanFile<"unresolved">): string {
  const { account } = file;
  const parser = parserLabel(file.parser_path);
  const who =
    account === null
      ? "but the parser reported no account identifier"
      : `and found it is a ${file.institution ?? "bank"} statement for ${account.kind === "card" ? "card" : "account"} identifier ${account.identifier}`;
  const identifierLine =
    account === null
      ? "Leave account_identifiers empty unless the statement prints an identifier the parser should be emitting."
      : `Set its account_identifiers to ["${account.identifier}"].`;
  const institution = file.institution_name;
  const found =
    institution === null
      ? "no institution in my import presets lists that parser"
      : `the institution "${institution}" in my import presets lists that parser but has no accounts`;
  const steps =
    institution === null
      ? `If an institution there already covers this bank, add ${parser} to it
(add_parser); otherwise add the institution with parsers ["${parser}"]
(add_institution). Then add my account to it (add_account).`
      : `Add my account to "${institution}" (add_account).`;
  return `The automatic statement importer of my books app (dbu6, run from this project) read ${file.file_name}
with ${parser} ${who}, but ${found}, so nothing was imported.
The upload is in this project at ${stagedAt(file)}.

${steps} Ask me for the account's name, its ledger account, whether it is a
credit card, and which custom_mappings_filenames to use if you cannot infer
them from the existing accounts. ${identifierLine}

${PRESET_CHANGES_NOTE}

Then tell me it is done and I will retry the import, or re-run it yourself.

${rerunBlock([stagedAt(file)])}`;
}

export function identifierRequiredPrompt(file: PlanFile<"unresolved">): string {
  return `The automatic statement importer of my books app (dbu6, run from this project) read ${file.file_name}
with ${file.parser_path}, but the parser emitted no \`account\` identifier and
the institution "${file.institution_name}" in my import presets needs one to
tell its accounts (${list(file.candidate_account_names)}) apart, so nothing
was imported.${quoted(file.message)}
The upload is in this project at ${stagedAt(file)}.
Either make the parser emit the account or card number the statement prints
(run \`${PARSER_GUIDE}\` and see its "Emitted account identifier" section)
with a sanitized fixture and test, or, if the statement genuinely prints no identifier, tell me
and we will decide whether to clear the account's identifiers
(update_account with account_identifiers []), which only an institution with
one account allows. Do not guess an identifier.
${PII_RULE}

${SAVED_PARSERS_NOTE} ${PROJECT_FILES_RULE}

${PRESET_CHANGES_NOTE}

Tell me when it is done and I will retry the import.`;
}

export function identifierMismatchPrompt(file: PlanFile<"unresolved">): string {
  const identifier = file.account?.identifier ?? null;
  const institution = file.institution_name;
  return `The automatic statement importer of my books app (dbu6, run from this project) read ${file.file_name}
with ${file.parser_path}. It reports account identifier ${identifier ?? "(none)"},
but none of the accounts of the institution "${institution}" in my import
presets (${list(file.candidate_account_names)}) lists it, so nothing was imported.${quoted(file.message)}
The upload is in this project at ${stagedAt(file)}.
Ask me which account the statement is for. If it is an account I have not set
up yet, add it to "${institution}" (add_account) with account_identifiers
["${identifier ?? "(ask me)"}"]; ask me for its name, its ledger account, and
whether it is a credit card. If it is one of the accounts above, printed
under another number, add the identifier to it (update_account with the
account's whole account_identifiers list, the new one included). Keep the
other accounts unchanged.

${PRESET_CHANGES_NOTE}

Tell me when it is done and I will retry the import.`;
}

// Where the failed account's uploads are, in the order the account holds
// them: the staged copies inside this project, for the agent to read and
// to post back.
function groupPaths(refusal: AccountRefusal): string[] {
  return refusal.failed_group.file_names.map(
    (name) =>
      refusal.files.find((file) => file.file_name === name)?.saved_path ?? name,
  );
}

// What every refusal prompt opens with: the account, its files and where they
// are, the error code as the server sent it, and the saved parsers that read
// those files.
function groupIntro(refusal: AccountRefusal): string {
  const group = refusal.failed_group;
  const parserPaths = Array.from(
    new Set(
      refusal.files.flatMap((file) =>
        file.status === "resolved" && group.file_names.includes(file.file_name)
          ? [file.parser_path]
          : [],
      ),
    ),
  );
  const parsers =
    parserPaths.length === 0
      ? "the saved parser"
      : `the saved parser (${list(parserPaths)})`;
  return `The automatic statement importer of my books app (dbu6, run from this project) refused to import
${list(group.file_names)} into ${group.account_name} (${group.base_account}) with
error ${refusal.error}. The files were read by ${parsers}.
The uploads are in this project at ${list(groupPaths(refusal))}.

${SAVED_PARSERS_NOTE} ${PROJECT_FILES_RULE}
`;
}

export function balanceMismatchPrompt(
  refusal: RefusalOf<"balance_mismatch" | "segment_balance_mismatch">,
): string {
  const numbers =
    refusal.error === "balance_mismatch"
      ? ` Computed final balance ${refusal.computed_final}, statement closing ${refusal.statement_closing}, difference ${refusal.difference}.`
      : ` From the balance ${refusal.from_balance} printed on ${refusal.from_date}, the rows lead to ${refusal.walked} on ${refusal.to_date}, where the statement prints ${refusal.printed}, difference ${refusal.difference}. The suspect rows are between ${refusal.from_date} and ${refusal.to_date}.`;
  return `${groupIntro(refusal)}${numbers}${quoted(refusal.message)}
Please find out why. Run the saved parser on those file(s) and compare its
output with the statement: check the opening and closing balances it emits,
every printed running balance, and whether the files together cover the whole
period with no gap. If a row is mis-parsed, fix the parser with a
sanitized fixture and a regression test, never by loosening validation. If the
statements leave a gap, tell me which dates are missing so I can download that
statement. ${PII_RULE}

Once fixed, you may re-run the import yourself or tell me and I will retry
from the screen.

${rerunBlock(groupPaths(refusal))}`;
}

export function boundaryGapPrompt(
  refusal: RefusalOf<"statement_boundary_mismatch">,
): string {
  return `${groupIntro(refusal)} ${refusal.earlier_source} ends at
${refusal.earlier_closing} and ${refusal.later_source} starts at ${refusal.later_opening},
difference ${refusal.difference}.${quoted(refusal.message)}
Run the saved parser on both files and tell me the exact last date of the
earlier one and the first date of the later one, and whether the difference
could be explained by rows at those edges rather than by a missing statement.
If a statement is missing, tell me which period to download. If the parser is
mis-reading an edge row, fix it with a sanitized fixture and test. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}

export function disagreementPrompt(
  refusal: RefusalOf<"statement_disagreement">,
): string {
  return `${groupIntro(refusal)} The parts disagree on ${refusal.date}
(${list(refusal.parts)}); the first differing row is ${JSON.stringify(refusal.row)}.${quoted(refusal.message)}
Run the saved parser on both files, print every row each one has on
${refusal.date}, and tell me which file is right, or whether both are and the
importer should accept this case, which is a change to dbu6 itself and not
something to patch here. If the parser is the cause, fix it with a sanitized fixture
and test. ${PII_RULE}

Then re-run the import with the correct file(s) or tell me which one to drop.

${rerunBlock(groupPaths(refusal))}`;
}

export function partInvalidPrompt(
  refusal: RefusalOf<"statement_part_invalid">,
): string {
  return `${groupIntro(refusal)} The part ${refusal.part} is not
self-consistent: ${refusal.detail}.${quoted(refusal.message)}
Run the saved parser on that file and compare its emitted opening, closing,
and running balances with what the statement prints. Decide whether the bank's
export is broken or the parser misreads it. If the parser is the cause, fix it
with a sanitized fixture and test, never by loosening validation. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}

export function reconciliationPrompt(
  refusal: RefusalOf<"reconciliation_match_failed">,
): string {
  return `${groupIntro(refusal)} The ledger's last reconciled
balance for that account is ${refusal.checkpoint_balance} on ${refusal.checkpoint_date},
but no statement row on that date carries that balance and the statement's
opening does not match it either.${quoted(refusal.message)}
Please compare the ledger and the statement around ${refusal.checkpoint_date}:
find the balance assertion for ${refusal.failed_group.base_account} on that date, list the
ledger postings for that account on and just before that date, run the saved
parser on the file and list the statement's rows for that day with their
printed balances, and tell me exactly where they diverge and what the correct
fix is (a missing or wrong entry in the ledger, or a statement problem). Do not
change the ledger or the assertion without telling me what you are about to
change and why. ${PII_RULE}

After the fix you may re-run the import.

${rerunBlock(groupPaths(refusal))}`;
}

export function missingAccountPrompt(
  refusal: RefusalOf<"import_account_not_found">,
): string {
  const { account_id, account_name } = refusal.failed_group;
  return `${groupIntro(refusal)} The account ${account_name} in my import presets
imports into the ledger account with id ${account_id}, which has been deleted,
so nothing was imported into it.${quoted(refusal.message)}
Ask me whether to recreate that ledger account (then ask me its name, its type
and which account it goes under, and add it to the Accounts table), or to
import into another account I have. Either way, point the preset account at
the ledger account: remove it (remove_account with account_id ${account_id})
and add it again with the new id (add_account), keeping its other fields.
Tell me what you changed.

${PRESET_CHANGES_NOTE}

Then re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}

export function closingBalancePrompt(
  refusal: RefusalOf<"closing_balance_unavailable">,
): string {
  return `${groupIntro(refusal)} This is a credit-card
statement and the parser emitted no closing balance and no printed running
balance on the last row, so the importer cannot verify it.${quoted(refusal.message)}
Check whether the statement prints a total amount due or closing balance. If
it does, make the parser emit it as \`closing\` through abacus.ledger_balance
(run \`${PARSER_GUIDE}\` for how), with a sanitized fixture and test. If it
truly prints none, stop and tell me what the statement
does print about the amount owed. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}

// For a code without a prompt of its own: the whole reply goes to the agent.
export function genericFailurePrompt(refusal: AccountRefusal): string {
  return `${groupIntro(refusal)}${quoted(refusal.message)}
The full error payload was:

${JSON.stringify(refusal, null, 2)}

Please find out what went wrong, starting from the error code and message
above and the file(s) named in it, and tell me what the fix is before changing
the ledger. ${PII_RULE}

Once fixed, you may re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}

// --- The setup wizard's sample statements --------------------------------

/** The account a sample statement was given for, as the wizard knows it. */
export interface SampleAccount {
  account_id: number;
  name: string;
  kind: "bank" | "card";
  institution: string;
  account_identifiers: readonly string[];
}

function sampleAccountLine(account: SampleAccount): string {
  const number =
    account.account_identifiers.length === 0
      ? "I haven't given its number yet"
      : `its number, as I typed it, is ${account.account_identifiers[0]}`;
  return `my ${account.kind === "card" ? "card" : "bank account"} "${account.name}"
(account_id ${account.account_id} in the import presets, in the institution
"${account.institution}"); ${number}`;
}

// The identifier step: set it when the account has none, else compare.
function sampleIdentifierStep(account: SampleAccount): string {
  return account.account_identifiers.length === 0
    ? `Set the account's number to the identifier the parser emits
   (update_account with account_id ${account.account_id} and account_identifiers
   ["<the identifier>"]).`
    : `Check that the identifier the parser emits is ${account.account_identifiers[0]}.
   If it isn't, don't change the account; tell me what the statement prints.`;
}

/**
 * The setup wizard's request for a parser, for a first statement no saved
 * parser recognized. It names the account, so the agent needn't ask whose
 * statement it is, and ties the parser to that account's institution. The
 * statement is imported once the parser reads it.
 */
export function sampleParserPrompt(
  account: SampleAccount,
  sample: { saved_path: string; tried: readonly string[] | null },
): string {
  const tried =
    sample.tried === null
      ? ""
      : sample.tried.length === 0
        ? " There is no saved parser at all for this file extension yet."
        : ` The parsers it tried and that rejected the file were: ${list(sample.tried)}.`;
  return `I am setting up my books app (dbu6, run from this project) and gave it the first
statement for ${sampleAccountLine(account)}. No saved parser recognised the
file.${tried} Please build a deterministic parser for this statement format.

The file is in this project at ${sample.saved_path}.
Don't import it yourself: the setup wizard imports it once the parser reads it.

${parserWritingSteps()}
6. Tie the parser to my account in the import presets, as below: add it to
   the institution "${account.institution}" by its directory name (add_parser).
   ${sampleIdentifierStep(account)}
7. Run the parser on that file and on the fixture, run the tests, and report
   the opening balance, closing balance, date range, and row count you found so
   I can check them against the statement.

${PRESET_CHANGES_NOTE}

When you are done, tell me. I will press Check again, and then import it.`;
}

/**
 * The setup wizard's request when a first statement matched more than one
 * saved parser: the import screen's, for the wizard's staged copy.
 */
export function sampleAmbiguousPrompt(
  account: SampleAccount,
  sample: { saved_path: string; parsers: readonly string[] },
): string {
  return `I am setting up my books app (dbu6, run from this project) and gave it the first
statement for ${sampleAccountLine(account)}. It matched more than one saved
parser: ${list(sample.parsers)}. Auto-detection requires exactly one match.

${fingerprintTightening(sample.saved_path)}

Tell me when it is done. I will press Check again, and then import it.`;
}
