// Prompts the user copies into their coding agent when the importer cannot
// go further on its own. Every prompt states what the app was doing, what
// it said (with the concrete facts from the response), what the agent should
// do, which guides govern the work, and what to report back.
// Prompts that let the agent retry the import end with `rerunBlock`.
//
// The app stages every upload of a batch it could not import under the
// project's own tmp/, so a prompt names the file by a path relative to the
// project the agent starts in and never asks the user to find it again.
//
// The guides ship inside dbu6, which in a user's project is an installed
// package: a prompt names the command that prints a guide (\`dbu6 docs\`),
// never a file of ours, and says that what the agent writes goes in the
// project's own directories.
//
// Each prompt takes the server's own reply for its case, a plan file or an
// account's refusal, and reads the contract's fields as they are named.

import { guideCommand, type AutoImportPlanFile } from "../../../shared/index";
import { PII_RULE, PROJECT_FILES_RULE } from "../../agent-prompt-rules";
import type { AccountRefusal, RefusalOf } from "./outcome";

type PlanFile<Status extends AutoImportPlanFile["status"]> = Extract<
  AutoImportPlanFile,
  { status: Status }
>;

const PARSERS_GUIDE = guideCommand("parsers");
const PARSER_GUIDE = guideCommand("parser-guide");

// A prompt names a parser as the app does, by its directory name.
const SAVED_PARSERS_NOTE = `A saved parser is named by its directory: the one of that name in this
project's custom-built-parsers/, or else the one bundled with dbu6, which
\`${PARSERS_GUIDE}\` lists.`;

function rerunBlock(paths: readonly string[]): string {
  const uploads = paths.map((path) => `    -F "files=@${path}"`).join(" \\\n");
  return `Re-running the import yourself: with the dev server running, POST the statement
file(s) to the same endpoint the screen uses. You need an agent access token,
which I can create from my account page in the app, in SAPPORTA_API_TOKEN.

  curl -sS -X POST "$SAPPORTA_API_URL/api/import-draft/statements/auto" \\
    -H "Authorization: Bearer $SAPPORTA_API_TOKEN" \\
${uploads}

A 200 response has \`files\` (how each upload was recognised and which preset it
went to) and \`groups\` (one per account: draft_transaction_count,
transaction_count, duplicate_count, skipped_reconciled_count,
balance_metadata, statement_period, reconciliation_checkpoint). Errors are
4xx/5xx JSON with an \`error\` code and a \`message\`. Imports only create Draft
transactions; they never post to the books.`;
}

// Where the agent will find an upload: the staged copy inside this
// project, or the name the user dropped when the app kept none.
function stagedAt(file: {
  file_name: string;
  saved_path: string | null;
}): string {
  return file.saved_path ?? file.file_name;
}

function quoted(message: string): string {
  return `\nServer message: "${message}"\n`;
}

function list(items: readonly string[]): string {
  return items.join(", ");
}

export function unrecognizedPrompt(file: PlanFile<"unrecognized">): string {
  const tried =
    file.candidate_parser_paths.length === 0
      ? "There is no saved parser at all for this file extension yet."
      : `The parsers it tried and that rejected the file were: ${list(file.candidate_parser_paths)}.`;
  return `I tried to import a bank statement into my books app (dbu6, run from this project) through
the automatic importer at /import. It said no saved parser
recognised the file, so nothing was imported. Please build a deterministic
parser for this statement format so the import works.

The file is in this project at ${stagedAt(file)}.
Ask me which bank and which of my accounts it belongs to if the file doesn't
make that obvious. ${tried}

Run \`${PARSERS_GUIDE}\` and \`${PARSER_GUIDE}\`, and follow the two guides
they print exactly. ${PROJECT_FILES_RULE} In particular:

1. Check whether an existing parser, in custom-built-parsers/ or among the
   bundled ones the first guide lists, already handles this bank and layout.
   Extend it only if it is the same bank and the same layout; otherwise add a
   new directory under custom-built-parsers/ with fingerprint.md, parser.py,
   parser_test.py, and a sanitized fixture generated by a script.
2. Inspect that file and write a strict fingerprint. The parser must reject
   any other layout and any malformed row instead of skipping it, and must only
   write output after every check passes.
3. Emit the account or card number the statement prints about itself as
   \`account\`, and the institution name exactly as printed as \`institution\`.
4. Validate the opening balance, the closing balance, every running balance the
   statement prints, and any totals it prints.
5. ${PII_RULE}
6. Add or update my account's entry in user-config/import-presets.json:
   set custom_statement_parser_path to the parser's directory name and
   statement_account_identifier to the identifier the parser emits. If no
   preset exists for this account yet, ask me for its name and ledger account
   (base_account) and whether it is a credit card.
7. Run the parser on that file and on the fixture, run the tests, and report
   the opening balance, closing balance, date range, and row count you found so
   I can check them against the statement.

When you are done, tell me. I will drop the file into the importer again myself.`;
}

export function ambiguousPrompt(file: PlanFile<"ambiguous">): string {
  return `The automatic statement importer of my books app (dbu6, run from this project)
(POST /api/import-draft/statements/auto, screen /import)
reported that ${file.file_name} matched more than one saved parser:
${list(file.matching_parser_paths)}. Auto-detection requires exactly one match,
so nothing was imported.

Tighten the fingerprints of those parsers (run \`${PARSERS_GUIDE}\` for the
conventions, and read each parser's fingerprint.md) so that each rejects the other's layout at
the first structural check, add a parser_test.py case in each that asserts the
other's fixture is rejected, and keep every existing fixture passing. Do not
loosen any validation to get there. ${PII_RULE}

${PROJECT_FILES_RULE}

The file is in this project at ${stagedAt(file)}.
Run each parser against it and confirm exactly one accepts it.

Tell me when it is done and I will retry the import.`;
}

export function noPresetPrompt(file: PlanFile<"unresolved">): string {
  const { account } = file;
  const who =
    account === null
      ? "but the parser reported no account identifier"
      : `and found it is a ${file.institution ?? "bank"} statement for ${account.kind === "card" ? "card" : "account"} identifier ${account.identifier}`;
  const identifierLine =
    account === null
      ? "Leave statement_account_identifier unset unless the statement prints an identifier the parser should be emitting."
      : `Set statement_account_identifier to ${account.identifier}.`;
  return `The automatic statement importer of my books app (dbu6, run from this project) read ${file.file_name}
with ${file.parser_path} ${who}, but no entry in
user-config/import-presets.json uses that parser, so nothing was imported.
The upload is in this project at ${stagedAt(file)}.

Add a preset for this account to user-config/import-presets.json. Ask me
for the account's display name, its ledger account (base_account), whether it
is a credit card, and which custom_mappings_filenames to use if you cannot
infer them from the existing presets. Set custom_statement_parser_path to
${file.parser_path}. ${identifierLine} Follow the shape of the existing
presets and what \`${PARSER_GUIDE}\` says about presets.

Then tell me it is done and I will retry the import, or re-run it yourself.

${rerunBlock([stagedAt(file)])}`;
}

export function identifierRequiredPrompt(file: PlanFile<"unresolved">): string {
  return `The automatic statement importer of my books app (dbu6, run from this project) read ${file.file_name}
with ${file.parser_path}, but the parser emitted no \`account\` identifier and
the preset(s) using that parser (${list(file.candidate_preset_names)}) require
one, so nothing was imported.${quoted(file.message)}
The upload is in this project at ${stagedAt(file)}.
Either make the parser emit the account or card number the statement prints
(run \`${PARSER_GUIDE}\` and see its "Emitted account identifier" section)
with a sanitized fixture and test, or, if the statement genuinely prints no identifier, tell me
and we will decide whether to drop statement_account_identifier from the
preset in user-config/import-presets.json. Do not guess an identifier.
${PII_RULE}

${SAVED_PARSERS_NOTE} ${PROJECT_FILES_RULE}

Tell me when it is done and I will retry the import.`;
}

export function identifierMismatchPrompt(file: PlanFile<"unresolved">): string {
  const identifier = file.account?.identifier ?? null;
  return `The automatic statement importer of my books app (dbu6, run from this project) read ${file.file_name}
with ${file.parser_path}. It reports account identifier ${identifier ?? "(none)"},
but the preset(s) that use this parser (${list(file.candidate_preset_names)})
carry a different statement_account_identifier, so nothing was imported.${quoted(file.message)}
The upload is in this project at ${stagedAt(file)}.
This is a statement for an account I have not set up yet. Add a new preset to
user-config/import-presets.json that shares custom_statement_parser_path
${file.parser_path} and has statement_account_identifier ${identifier ?? "(ask me)"}.
Ask me for its display name, ledger account (base_account), and whether it is
a credit card. Keep the existing presets unchanged.

Tell me when it is done and I will retry the import.`;
}

// Where the failed account's uploads are, in the order the account holds
// them: the staged copies inside this project, for the agent to read and
// to post back.
function groupPaths(refusal: AccountRefusal): string[] {
  return refusal.failed_group.file_names.map(
    (name) =>
      refusal.files.find((file) => file.file_name === name)?.saved_path ?? name,
  );
}

// What every refusal prompt opens with: the account, its files and where they
// are, the error code as the server sent it, and the saved parsers that read
// those files.
function groupIntro(refusal: AccountRefusal): string {
  const group = refusal.failed_group;
  const parserPaths = Array.from(
    new Set(
      refusal.files.flatMap((file) =>
        file.status === "resolved" && group.file_names.includes(file.file_name)
          ? [file.parser_path]
          : [],
      ),
    ),
  );
  const parsers =
    parserPaths.length === 0
      ? "the saved parser"
      : `the saved parser (${list(parserPaths)})`;
  return `The automatic statement importer of my books app (dbu6, run from this project) refused to import
${list(group.file_names)} into ${group.preset_name} (${group.base_account}) with
error ${refusal.error}. The files were read by ${parsers}.
The uploads are in this project at ${list(groupPaths(refusal))}.

${SAVED_PARSERS_NOTE} ${PROJECT_FILES_RULE}
`;
}

export function balanceMismatchPrompt(
  refusal: RefusalOf<"balance_mismatch" | "segment_balance_mismatch">,
): string {
  const numbers =
    refusal.error === "balance_mismatch"
      ? ` Computed final balance ${refusal.computed_final}, statement closing ${refusal.statement_closing}, difference ${refusal.difference}.`
      : ` From the balance ${refusal.from_balance} printed on ${refusal.from_date}, the rows lead to ${refusal.walked} on ${refusal.to_date}, where the statement prints ${refusal.printed}, difference ${refusal.difference}. The suspect rows are between ${refusal.from_date} and ${refusal.to_date}.`;
  return `${groupIntro(refusal)}${numbers}${quoted(refusal.message)}
Please find out why. Run the saved parser on those file(s) and compare its
output with the statement: check the opening and closing balances it emits,
every printed running balance, and whether the files together cover the whole
period with no gap. If a row is mis-parsed, fix the parser with a
sanitized fixture and a regression test, never by loosening validation. If the
statements leave a gap, tell me which dates are missing so I can download that
statement. ${PII_RULE}

Once fixed, you may re-run the import yourself or tell me and I will retry
from the screen.

${rerunBlock(groupPaths(refusal))}`;
}

export function boundaryGapPrompt(
  refusal: RefusalOf<"statement_boundary_mismatch">,
): string {
  return `${groupIntro(refusal)} ${refusal.earlier_source} ends at
${refusal.earlier_closing} and ${refusal.later_source} starts at ${refusal.later_opening},
difference ${refusal.difference}.${quoted(refusal.message)}
Run the saved parser on both files and tell me the exact last date of the
earlier one and the first date of the later one, and whether the difference
could be explained by rows at those edges rather than by a missing statement.
If a statement is missing, tell me which period to download. If the parser is
mis-reading an edge row, fix it with a sanitized fixture and test. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}

export function disagreementPrompt(
  refusal: RefusalOf<"statement_disagreement">,
): string {
  return `${groupIntro(refusal)} The parts disagree on ${refusal.date}
(${list(refusal.parts)}); the first differing row is ${JSON.stringify(refusal.row)}.${quoted(refusal.message)}
Run the saved parser on both files, print every row each one has on
${refusal.date}, and tell me which file is right, or whether both are and the
importer should accept this case, which is a change to dbu6 itself and not
something to patch here. If the parser is the cause, fix it with a sanitized fixture
and test. ${PII_RULE}

Then re-run the import with the correct file(s) or tell me which one to drop.

${rerunBlock(groupPaths(refusal))}`;
}

export function partInvalidPrompt(
  refusal: RefusalOf<"statement_part_invalid">,
): string {
  return `${groupIntro(refusal)} The part ${refusal.part} is not
self-consistent: ${refusal.detail}.${quoted(refusal.message)}
Run the saved parser on that file and compare its emitted opening, closing,
and running balances with what the statement prints. Decide whether the bank's
export is broken or the parser misreads it. If the parser is the cause, fix it
with a sanitized fixture and test, never by loosening validation. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}

export function reconciliationPrompt(
  refusal: RefusalOf<"reconciliation_match_failed">,
): string {
  return `${groupIntro(refusal)} The ledger's last reconciled
balance for that account is ${refusal.checkpoint_balance} on ${refusal.checkpoint_date},
but no statement row on that date carries that balance and the statement's
opening does not match it either.${quoted(refusal.message)}
Please compare the ledger and the statement around ${refusal.checkpoint_date}:
find the balance assertion for ${refusal.failed_group.base_account} on that date, list the
ledger postings for that account on and just before that date, run the saved
parser on the file and list the statement's rows for that day with their
printed balances, and tell me exactly where they diverge and what the correct
fix is (a missing or wrong entry in the ledger, or a statement problem). Do not
change the ledger or the assertion without telling me what you are about to
change and why. ${PII_RULE}

After the fix you may re-run the import.

${rerunBlock(groupPaths(refusal))}`;
}

export function missingAccountPrompt(
  refusal: RefusalOf<"import_account_not_found">,
): string {
  const { preset_name, base_account } = refusal.failed_group;
  return `${groupIntro(refusal)} The preset ${preset_name} in
user-config/import-presets.json imports into ${base_account}, but the
ledger has no account by that name, so nothing was imported into it.${quoted(refusal.message)}
Ask me whether ${base_account} is a new account or a different name for one I
already have. For a new one, ask me its type and which account it goes under,
and add it to the Accounts table. Otherwise set the preset's base_account to
that account's name exactly as Accounts lists it. Tell me what you changed.

Then re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}

export function closingBalancePrompt(
  refusal: RefusalOf<"closing_balance_unavailable">,
): string {
  return `${groupIntro(refusal)} This is a credit-card
statement and the parser emitted no closing balance and no printed running
balance on the last row, so the importer cannot verify it.${quoted(refusal.message)}
Check whether the statement prints a total amount due or closing balance. If
it does, make the parser emit it as \`closing\` through abacus.ledger_balance
(run \`${PARSER_GUIDE}\` for how), with a sanitized fixture and test. If it
truly prints none, stop and tell me what the statement
does print about the amount owed. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}

// For a code without a prompt of its own: the whole reply goes to the agent.
export function genericFailurePrompt(refusal: AccountRefusal): string {
  return `${groupIntro(refusal)}${quoted(refusal.message)}
The full error payload was:

${JSON.stringify(refusal, null, 2)}

Please find out what went wrong, starting from the error code and message
above and the file(s) named in it, and tell me what the fix is before changing
the ledger. ${PII_RULE}

Once fixed, you may re-run the import yourself or tell me and I will retry.

${rerunBlock(groupPaths(refusal))}`;
}
