// Barrel for ts-rest contracts. Add one file per feature and re-export its
// router from here so `src/shared/index.ts` can pick everything up in
// one place.

export {
  reportsContract,
  incomeExpensesAccountSchema,
  incomeExpensesSchema,
  type IncomeExpenses,
  type IncomeExpensesAccount,
} from "./reports.js";
export {
  importDraftsContract,
  importSummarySchema,
  categorizationReportSchema,
  type CategorizationReport,
  categorizationFailureSchema,
  type CategorizationFailure,
  categorizationTallySchema,
  type CategorizationTally,
  statementImportResultSchema,
  sameAccountSkipSchema,
  autoImportPlanFileSchema,
  autoImportGroupResultSchema,
  autoImportResultSchema,
  abacusImportResultSchema,
  autoImportErrorSchema,
  type AutoImportPlanFile,
  type AutoImportGroupResult,
  type AbacusImportResult,
  type AutoImportResult,
  type AutoImportFailedGroup,
  type AutoImportErrorBody,
  type StatementImportResultBody,
} from "./import-drafts.js";
export {
  statementImportErrorSchema,
  type StatementImportError,
  type StatementImportErrorCode,
} from "./import-errors.js";
export {
  accountKindSchema,
  accountKindOf,
  accountKindOfType,
  LEDGER_ACCOUNT_TYPE,
  type AccountKind,
} from "./account-kind.js";
export {
  draftCountsSchema,
  NO_DRAFTS,
  POSTING_CHECK_KINDS,
  postingCheck,
  postingChecks,
  postingBlocks,
  isBlock,
  isProblem,
  type DraftCounts,
  type PostingCheck,
  type PostingCheckKind,
  type PostingBlock,
  type ProblemBlock,
} from "./posting-checks.js";
export { datedBalanceSchema, type DatedBalance } from "./dated-balance.js";
export { dateSpanSchema, type DateSpan } from "./date-span.js";
export {
  abacusImportRequestSchema,
  abacusJsonSchema,
  abacusRowSchema,
  depositMoneySchema,
  withdrawalMoneySchema,
  type AbacusImportRequest,
  type AbacusJson,
} from "./abacus.js";
export {
  accountInstructionsSchema,
  customMappingsFileSchema,
  importAccountSchema,
  importAccountViewSchema,
  importInstitutionSchema,
  importPresetChangeSchema,
  importPresetRefusalCodeSchema,
  importPresetRefusalSchema,
  importPresetsContract,
  importPresetsFileConversionSchema,
  importPresetsFileRefusalSchema,
  importPresetsViewSchema,
  mappingFilenameSchema,
  parserNameSchema,
  transactionMappingsViewSchema,
  type AccountInstructions,
  type CustomMappingsFile,
  type ImportAccount,
  type ImportAccountView,
  type ImportInstitution,
  type ImportPresetChange,
  type ImportPresetRefusal,
  type ImportPresetRefusalCode,
  type ImportPresetsFileConversionBody,
  type ImportPresetsFileRefusal,
  type ImportPresetsView,
  type TransactionMappingsView,
} from "./import-presets.js";
export {
  canonicalStatementIdentifier,
  statementAccountSchema,
  statementAccountIdentifierSchema,
  statementAccountKindSchema,
  type StatementAccount,
  type StatementAccountKind,
} from "./statement-account.js";
export {
  draftTransactionsContract,
  draftClassificationSchema,
  gpayDraftClassificationSchema,
  type DraftClassification,
  type GPayDraftClassification,
} from "./draft-transactions.js";
export {
  categorizationLessonSchema,
  categorizationLessonsContract,
  type CategorizationLesson,
} from "./categorization-lessons.js";
export {
  agentModelSchema,
  agentModelsSchema,
  codingAgentContract,
  codingAgentSchema,
  codingAgentSettingsSchema,
  codingAgentStatusSchema,
  chooseCodingAgentRequestSchema,
  noAgentModelMessage,
  ANY_CODING_AGENT,
  CODING_AGENTS,
  NO_CODING_AGENT_MESSAGE,
  unavailableAgentModelSchema,
  type AgentModel,
  type AgentModels,
  type CodingAgent,
  type CodingAgentSettings,
  type CodingAgentStatus,
  type UnavailableAgentModel,
} from "./coding-agent.js";
export {
  agentHandoffContract,
  agentHandoffAvailabilitySchema,
  agentHandoffModeSchema,
  agentHandoffRequestSchema,
  agentHandoffSchema,
  agentHandoffErrorSchema,
  type AgentHandoffAvailability,
  type AgentHandoffMode,
  type AgentHandoffRequest,
  type AgentHandoff,
  type AgentHandoffErrorBody,
} from "./agent-handoff.js";
export { journalsContract } from "./journals.js";
export {
  homeContract,
  homeAccountSchema,
  homeSummarySchema,
  type HomeAccount,
  type HomeLedgerAccount,
  type HomeSummary,
} from "./home.js";
export {
  reviewContract,
  reviewAccountSchema,
  reviewAccountDetailSchema,
  reviewDuplicateSchema,
  reviewFailingCheckSchema,
  type ReviewAccount,
  type ReviewAccountDetail,
  type ReviewDuplicate,
  type ReviewFailingCheck,
} from "./review.js";
export {
  openingBalancesContract,
  openingBalanceAccountSchema,
  openingBalanceRefusalSchema,
  openingBalancesSchema,
  openingEntrySchema,
  openingLockSchema,
  openingSectionSchema,
  type OpeningBalanceAccount,
  type OpeningBalanceRefusal,
  type OpeningBalances,
  type OpeningEntry,
  type OpeningLock,
  type OpeningSection,
} from "./opening-balances.js";
export {
  setupContract,
  chartAccountSchema,
  chartInTreeOrder,
  chartProposalSchema,
  chartOfAccountsSchema,
  chartRefusalSchema,
  chartSuggesterSchema,
  chartSuggestionRefusalSchema,
  chartSuggestionRequestSchema,
  chartSuggestionSchema,
  ledgerAccountTypeSchema,
  statementAccountChangeSchema,
  statementAccountRefusalSchema,
  statementAccountRowSchema,
  statementAccountsSchema,
  LEDGER_ACCOUNT_TYPES,
  OPENING_BALANCES_NAME,
  type ChartAccount,
  type ChartOfAccounts,
  type ChartProposal,
  type ChartRefusal,
  type ChartRow,
  type ChartSuggester,
  type ChartSuggestion,
  type LedgerAccountType,
  type ChartChoice,
  type StatementAccountChange,
  type StatementAccountRefusal,
  type StatementAccountRow,
  type StatementAccounts,
} from "./setup.js";
export {
  addAccountContract,
  addAccountFileSchema,
  addAccountStatusSchema,
  addAccountCandidateSchema,
  addAccountReadingSchema,
  addAccountFieldsSchema,
  addAccountAddedSchema,
  addAccountRefusalSchema,
  refusalPromptsAgent,
  categorizerStatusSchema,
  statementOpeningSchema,
  type CategorizerStatus,
  type StatementOpening,
  type AddAccountFile,
  type AddAccountStatus,
  type AddAccountCandidate,
  type AddAccountReading,
  type AddAccountFields,
  type AddAccountAdded,
  type AddAccountRefusal,
} from "./add-account.js";
