// Prompts the user copies into their coding agent when the importer cannot
// go further on its own. Every prompt states what the app was doing, what
// it said (with the concrete facts from the response), what the agent should
// do, which repository documents govern the work, and what to report back.
// Prompts that let the agent retry the import end with `RERUN_BLOCK`.

export const RERUN_BLOCK = `Re-running the import yourself: with the dev server running, POST the statement
file(s) to the same endpoint the screen uses. You need an agent access token,
which I can create from my account page in the app, in SAPPORTA_API_TOKEN.

  curl -sS -X POST "$SAPPORTA_API_URL/api/import-draft/statements/auto" \\
    -H "Authorization: Bearer $SAPPORTA_API_TOKEN" \\
    -F "files=@/path/to/statement.xls"

A 200 response has \`files\` (how each upload was recognised and which preset it
went to) and \`groups\` (one per account: draft_transaction_count,
transaction_count, duplicate_count, skipped_reconciled_count,
balance_metadata, statement_period, reconciliation_checkpoint). Errors are
4xx/5xx JSON with an \`error\` code and a \`message\`. Imports only create Draft
transactions; they never post to the books.`;

const PII_RULE = `Never put real names, account numbers, references, or amounts in the
repository. Use the 050505 / NOPII / sample conventions in AGENTS.md for any
fixture or test.`;

function quoted(message: string | null): string {
  return message === null ? "" : `\nServer message: "${message}"\n`;
}

function list(items: readonly string[]): string {
  return items.join(", ");
}

export function unrecognizedPrompt(facts: {
  fileName: string;
  candidateParserPaths: readonly string[];
}): string {
  const tried =
    facts.candidateParserPaths.length === 0
      ? "There is no saved parser at all for this file extension yet."
      : `The parsers it tried and that rejected the file were: ${list(facts.candidateParserPaths)}.`;
  return `I tried to import a bank statement into my books app (this repository) through
the automatic importer at /views/import-statements. It said no saved parser
recognised the file, so nothing was imported. Please build a deterministic
parser for this statement format so the import works.

The file is called ${facts.fileName}. Ask me where it is on disk if you can't
find it, and ask me which bank and which of my accounts it belongs to if the
file doesn't make that obvious. ${tried}

Follow custom-built-parsers/README.md and
custom-built-parsers/import-statement-parser-guide.md exactly. In particular:

1. Check whether an existing parser under custom-built-parsers/ already handles
   this bank and layout. Extend it only if it is the same bank and the same
   layout; otherwise add a new directory with fingerprint.md, parser.py,
   parser_test.py, and a sanitized fixture generated by a script.
2. Inspect the real file and write a strict fingerprint. The parser must reject
   any other layout and any malformed row instead of skipping it, and must only
   write output after every check passes.
3. Emit the account or card number the statement prints about itself as
   \`account\`, and the institution name exactly as printed as \`institution\`.
4. Validate the opening balance, the closing balance, every running balance the
   statement prints, and any totals it prints.
5. ${PII_RULE}
6. Add or update my account's entry in data/user-config/import-presets.json:
   set custom_statement_parser_path to the parser and
   statement_account_identifier to the identifier the parser emits. If no
   preset exists for this account yet, ask me for its name and ledger account
   (base_account) and whether it is a credit card.
7. Run the parser on my real file and on the fixture, run the tests, and report
   the opening balance, closing balance, date range, and row count you found so
   I can check them against the statement.

When you are done, tell me. I will drop the file into the importer again myself.`;
}

export function ambiguousPrompt(facts: {
  fileName: string;
  matchingParserPaths: readonly string[];
}): string {
  return `The automatic statement importer in this repository
(POST /api/import-draft/statements/auto, screen /views/import-statements)
reported that ${facts.fileName} matched more than one saved parser:
${list(facts.matchingParserPaths)}. Auto-detection requires exactly one match,
so nothing was imported.

Tighten the fingerprints of those parsers (see custom-built-parsers/README.md
and each parser's fingerprint.md) so that each rejects the other's layout at
the first structural check, add a parser_test.py case in each that asserts the
other's fixture is rejected, and keep every existing fixture passing. Do not
loosen any validation to get there. Ask me for the real file if you need it.
${PII_RULE}

Then run each parser against my real file and confirm exactly one accepts it.
Tell me when it is done and I will retry the import.`;
}

export function noPresetPrompt(facts: {
  fileName: string;
  parserPath: string;
  institution: string | null;
  identifier: string | null;
  kind: "bank" | "card" | null;
}): string {
  const who =
    facts.identifier === null
      ? "but the parser reported no account identifier"
      : `and found it is a ${facts.institution ?? "bank"} statement for ${facts.kind === "card" ? "card" : "account"} identifier ${facts.identifier}`;
  const identifierLine =
    facts.identifier === null
      ? "Leave statement_account_identifier unset unless the statement prints an identifier the parser should be emitting."
      : `Set statement_account_identifier to ${facts.identifier}.`;
  return `The automatic statement importer in this repository read ${facts.fileName}
with ${facts.parserPath} ${who}, but no entry in
data/user-config/import-presets.json uses that parser, so nothing was imported.

Add a preset for this account to data/user-config/import-presets.json. Ask me
for the account's display name, its ledger account (base_account), whether it
is a credit card, and which custom_mappings_filenames to use if you cannot
infer them from the existing presets. Set custom_statement_parser_path to
${facts.parserPath}. ${identifierLine} Follow the shape documented in
packages/shared/src/contracts/import-presets.ts and the examples in
user-config.example/import-presets.json.

Then tell me it is done and I will retry the import, or re-run it yourself with
the file I give you.

${RERUN_BLOCK}`;
}

export function identifierRequiredPrompt(facts: {
  fileName: string;
  parserPath: string;
  candidatePresetNames: readonly string[];
  message: string | null;
}): string {
  return `The automatic statement importer in this repository read ${facts.fileName}
with ${facts.parserPath}, but the parser emitted no \`account\` identifier and
the preset(s) using that parser (${list(facts.candidatePresetNames)}) require
one, so nothing was imported.${quoted(facts.message)}
Either make the parser emit the account or card number the statement prints
(see the "Emitted account identifier" section of
custom-built-parsers/import-statement-parser-guide.md) with a sanitized
fixture and test, or, if the statement genuinely prints no identifier, tell me
and we will decide whether to drop statement_account_identifier from the
preset in data/user-config/import-presets.json. Do not guess an identifier.
${PII_RULE}

Tell me when it is done and I will retry the import.`;
}

export function identifierMismatchPrompt(facts: {
  fileName: string;
  parserPath: string;
  identifier: string | null;
  candidatePresetNames: readonly string[];
  message: string | null;
}): string {
  return `The automatic statement importer in this repository read ${facts.fileName}
with ${facts.parserPath}. It reports account identifier ${facts.identifier ?? "(none)"},
but the preset(s) that use this parser (${list(facts.candidatePresetNames)})
carry a different statement_account_identifier, so nothing was imported.${quoted(facts.message)}
This is a statement for an account I have not set up yet. Add a new preset to
data/user-config/import-presets.json that shares custom_statement_parser_path
${facts.parserPath} and has statement_account_identifier ${facts.identifier ?? "(ask me)"}.
Ask me for its display name, ledger account (base_account), and whether it is
a credit card. Keep the existing presets unchanged.

Tell me when it is done and I will retry the import.`;
}

export interface FailedGroupFacts {
  fileNames: readonly string[];
  presetName: string;
  baseAccount: string;
  parserPaths: readonly string[];
  message: string | null;
}

function groupIntro(facts: FailedGroupFacts, code: string): string {
  const parsers =
    facts.parserPaths.length === 0
      ? "the saved parser"
      : `the saved parser (${list(facts.parserPaths)})`;
  return `The automatic statement importer in this repository refused to import
${list(facts.fileNames)} into ${facts.presetName} (${facts.baseAccount}) with
error ${code}. The files were read by ${parsers}.`;
}

export function balanceMismatchPrompt(
  facts: FailedGroupFacts & {
    computedFinal: number | null;
    statementClosing: number | null;
    difference: number | null;
    suspectRange: { fromDate: string; toDate: string } | null;
  },
): string {
  const numbers =
    facts.computedFinal === null
      ? ""
      : ` Computed final balance ${facts.computedFinal}, statement closing ${facts.statementClosing}, difference ${facts.difference}.`;
  const range =
    facts.suspectRange === null
      ? ""
      : ` The suspect rows are between ${facts.suspectRange.fromDate} and ${facts.suspectRange.toDate}.`;
  return `${groupIntro(facts, facts.suspectRange ? "segment_balance_mismatch" : "balance_mismatch")}${numbers}${range}${quoted(facts.message)}
Please find out why. Run the saved parser on the file(s) I give you and compare
its output with the statement: check the opening and closing balances it
emits, every printed running balance, and whether the files together cover the
whole period with no gap. If a row is mis-parsed, fix the parser with a
sanitized fixture and a regression test, never by loosening validation. If the
statements leave a gap, tell me which dates are missing so I can download that
statement. ${PII_RULE}

Once fixed, you may re-run the import yourself or tell me and I will retry
from the screen.

${RERUN_BLOCK}`;
}

export function boundaryGapPrompt(
  facts: FailedGroupFacts & {
    earlierSource: string;
    laterSource: string;
    earlierClosing: number | null;
    laterOpening: number | null;
    difference: number | null;
  },
): string {
  return `${groupIntro(facts, "statement_boundary_mismatch")} ${facts.earlierSource} ends at
${facts.earlierClosing} and ${facts.laterSource} starts at ${facts.laterOpening},
difference ${facts.difference}.${quoted(facts.message)}
Run the saved parser on both files and tell me the exact last date of the
earlier one and the first date of the later one, and whether the difference
could be explained by rows at those edges rather than by a missing statement.
If a statement is missing, tell me which period to download. If the parser is
mis-reading an edge row, fix it with a sanitized fixture and test. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${RERUN_BLOCK}`;
}

export function disagreementPrompt(
  facts: FailedGroupFacts & {
    date: string;
    parts: readonly string[];
    row: string;
  },
): string {
  return `${groupIntro(facts, "statement_disagreement")} The parts disagree on ${facts.date}
(${list(facts.parts)}); the first differing row is ${facts.row}.${quoted(facts.message)}
Run the saved parser on both files, print every row each one has on
${facts.date}, and tell me which file is right, or whether both are and the
importer's assembly in packages/api/bank-importer/abacus/assemble.ts should
accept this case. If the parser is the cause, fix it with a sanitized fixture
and test. ${PII_RULE}

Then re-run the import with the correct file(s) or tell me which one to drop.

${RERUN_BLOCK}`;
}

export function partInvalidPrompt(
  facts: FailedGroupFacts & { part: string; detail: string | null },
): string {
  return `${groupIntro(facts, "statement_part_invalid")} The part ${facts.part} is not
self-consistent: ${facts.detail ?? "(no detail)"}.${quoted(facts.message)}
Run the saved parser on that file and compare its emitted opening, closing,
and running balances with what the statement prints. Decide whether the bank's
export is broken or the parser misreads it. If the parser is the cause, fix it
with a sanitized fixture and test, never by loosening validation. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${RERUN_BLOCK}`;
}

export function reconciliationPrompt(
  facts: FailedGroupFacts & {
    checkpointDate: string | null;
    checkpointBalance: number | null;
  },
): string {
  return `${groupIntro(facts, "reconciliation_match_failed")} The ledger's last reconciled
balance for that account is ${facts.checkpointBalance} on ${facts.checkpointDate},
but no statement row on that date carries that balance and the statement's
opening does not match it either.${quoted(facts.message)}
Please compare the ledger and the statement around ${facts.checkpointDate}:
find the balance assertion for ${facts.baseAccount} on that date, list the
ledger postings for that account on and just before that date, run the saved
parser on the file and list the statement's rows for that day with their
printed balances, and tell me exactly where they diverge and what the correct
fix is (a missing or wrong entry in the ledger, or a statement problem). Do not
change the ledger or the assertion without telling me what you are about to
change and why. ${PII_RULE}

After the fix you may re-run the import.

${RERUN_BLOCK}`;
}

export function openingBalancePrompt(facts: FailedGroupFacts): string {
  return `${groupIntro(facts, "opening_balance_unavailable")} The statement prints no
running balances and no opening balance, and the ledger has no reconciled
balance for ${facts.baseAccount} yet, so the importer cannot compute the
balances.${quoted(facts.message)}
Ask me for the opening balance printed on the statement (or the balance the
day before it starts). Then add a balance assertion for ${facts.baseAccount}
on the day before the statement's first transaction with that amount, following
how balance assertions are recorded in this repository, and tell me what you
added. If the parser could have emitted an opening balance the statement does
print, fix the parser instead, with a sanitized fixture and test. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${RERUN_BLOCK}`;
}

export function closingBalancePrompt(facts: FailedGroupFacts): string {
  return `${groupIntro(facts, "closing_balance_unavailable")} This is a credit-card
statement and the parser emitted no closing balance and no printed running
balance on the last row, so the importer cannot verify it.${quoted(facts.message)}
Check whether the statement prints a total amount due or closing balance. If
it does, make the parser emit it as \`closing\` through abacus.ledger_balance
(see custom-built-parsers/import-statement-parser-guide.md), with a sanitized
fixture and test. If it truly prints none, stop and tell me what the statement
does print about the amount owed. ${PII_RULE}

Then re-run the import yourself or tell me and I will retry.

${RERUN_BLOCK}`;
}

export function genericFailurePrompt(
  facts: FailedGroupFacts & { code: string; payload: string },
): string {
  return `${groupIntro(facts, facts.code)}${quoted(facts.message)}
The full error payload was:

${facts.payload}

Please find out what went wrong, starting from the error class in
packages/api/bank-importer/import-errors.ts and the import pipeline in
packages/api/bank-importer/statement-import.ts, and tell me what the fix is
before changing the ledger. ${PII_RULE}

Once fixed, you may re-run the import yourself or tell me and I will retry.

${RERUN_BLOCK}`;
}
