// The parts of a coding-agent prompt about writing parsers, the same
// wherever the app asks for one: /import when it can't read a file, and
// /add's Teach card. Each screen writes its own prompt around them.
import { guideCommand } from "../shared/index";
import { PII_RULE, PROJECT_FILES_RULE } from "./agent-prompt-rules";

const PARSERS_GUIDE = guideCommand("parsers");
const PARSER_GUIDE = guideCommand("parser-guide");
const BOOKS_GUIDE = guideCommand("books");

// How a prompt has the agent change the import presets: the app's
// import_presets table, one institution per row with the parsers that read
// its statements and the accounts they import into. Changes go through the
// one route that checks them, never through a file.
export const PRESET_CHANGES_NOTE = `The import presets are in the app, one institution per row, each listing the
saved parsers that read its statements and the accounts they import into.
Change them only through the app, never by editing a file:

  sapporta api get /api/import-presets
  sapporta api post /api/import-presets/changes --body '{"changes":[...]}'

An account names its ledger account by id; find it with
\`sapporta rows list accounts --where '{"name":{"eq":"<name>"}}'\`.
Run \`${BOOKS_GUIDE}\` for these calls and each change's fields.`;

/** Which saved parsers turned a file down, for a prompt to say. */
export function triedParsers(candidateParserPaths: readonly string[]): string {
  return candidateParserPaths.length === 0
    ? "There is no saved parser at all for this file extension yet."
    : `The parsers it tried and that rejected the file were: ${candidateParserPaths.join(", ")}.`;
}

/**
 * How a parser is written: the guides, then steps 1 to 5. The caller
 * numbers on from 6.
 */
export function parserWritingSteps(): string {
  return `Run \`${PARSERS_GUIDE}\` and \`${PARSER_GUIDE}\`, and follow the two guides
they print exactly. ${PROJECT_FILES_RULE} In particular:

1. Check whether an existing parser, in custom-built-parsers/ or among the
   bundled ones the first guide lists, already handles this bank and layout.
   Extend it only if it is the same bank and the same layout; otherwise add a
   new directory under custom-built-parsers/ with fingerprint.md, parser.py,
   parser_test.py, and a sanitized fixture generated by a script.
2. Inspect that file and write a strict fingerprint. The parser must reject
   any other layout and any malformed row instead of skipping it, and must only
   write output after every check passes.
3. Emit the account or card number the statement prints about itself as
   \`account\`, and the institution name exactly as printed as \`institution\`.
4. Validate the opening balance, the closing balance, every running balance the
   statement prints, and any totals it prints.
5. ${PII_RULE}`;
}

/** Two parsers claim one file: how to part them, for the file at `path`. */
export function fingerprintTightening(path: string): string {
  return `Tighten the fingerprints of those parsers (run \`${PARSERS_GUIDE}\` for the
conventions, and read each parser's fingerprint.md) so that each rejects the other's layout at
the first structural check, add a parser_test.py case in each that asserts the
other's fixture is rejected, and keep every existing fixture passing. Do not
loosen any validation to get there. ${PII_RULE}

${PROJECT_FILES_RULE}

The file is in this project at ${path}.
Run each parser against it and confirm exactly one accepts it.`;
}
